# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: "ap-south-1"

      - name: Setup Git
        run: |
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git config --global user.name "Vinod S R"

      - name: Increment patch version
        run: npm version patch

      - name: Push version changes
        run: git push "https://${{secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"

      - name: Install deps
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Build App
        run: npm run build

      - name: Deploy to S3 - Dev
        run: aws s3 sync ./build s3://convertall-dev

      - name: Dev - Cloudfront Invalidation
        run: aws cloudfront create-invalidation --distribution-id  E2XIFKJU7Z6T0E  --paths "/*"
